[package]
name = "idg"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
ndarray = "0.17.2"
ndarray-rand = "0.16.0"
num-complex = "0.4.6"
num-traits = "0.2.19"
